<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Ebooks</title>
    <link rel="shortcut icon" href="http://www.polyinnovations.com/images/e-book.png" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="/css/app.css">
    <link rel="stylesheet" type="text/css" href="/css/selectivity.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <!--    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>-->
</head>
<body>

{% block content %}{% endblock %}

<script src="//code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="/js/app.js"></script>
<script type="text/javascript" charset="utf8" src="/js/selectivity-3.0.6/selectivity-jquery.js"></script>
<script type="text/javascript" charset="utf8" src="/js/selectivity-3.0.6/selectivity.js"></script>

</body>
</html>
